Add VIA support for Keychron V10
the-via/keyboards pull request #1673
Opened 2023-02-06 02:38 UTC by lalalademaxiya1

As the title.

## Description

- Add VIA JSONs for Keychron V10.

1. Add ANSI and ISO versions, enable encoder support.
2. Add encoder ID (e0) as the center label for encoder keys to support encoder mapping.
3. Added JSONs to src and v3.

## QMK Pull Request 

qmk/qmk_firmware#19504

## Checklist

- [x] The VIA support for this keyboard is in QMK master already **(MANDATORY)**
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

2023-02-09 06:48 UTC, Xelus22 requested changes
PID does not match for the ANSI versions

2023-02-09 10:35 UTC, lalalademaxiya1 commented
@Xelus22 Hi, It is correct in JSONs but not in QMK. I will fix the issue in QMK, Thanks~

2023-02-10 06:02 UTC, keychron-dev commented
@Xelus22 now, it's fixed, please have another look. thanks

2023-02-10 07:17 UTC, Xelus22 approved these changes

2023-02-10 07:17 UTC, merged