Add Degenpad
the-via/keyboards pull request #1692
Opened 2023-02-12 01:12 UTC by ThePanduuh

## Description

## QMK Pull Request 

https://github.com/qmk/qmk_firmware/pull/19812

## Checklist

- [ ] The VIA support for this keyboard is in QMK master already **(MANDATORY)**
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

2023-02-14 14:38 UTC, MaiTheSan requested changes

2023-02-14 14:38 UTC, MaiTheSan commented on v3/thepanduuh/degenpad.json
> +  "productId": "0x0000",
```suggestion
  "productId": "0x4447",
```

2023-02-14 14:38 UTC, MaiTheSan commented on v3/thepanduuh/degenpad.json
> +  "vendorId": "0x0000",
```suggestion
  "vendorId": "0x4A44",
```

2023-02-14 14:38 UTC, MaiTheSan commented on src/thepanduuh/degenpad/degenpad.json
> +  "menus": [],
```suggestion
  "lighting":"none",
```

2023-02-14 14:38 UTC, MaiTheSan commented on src/thepanduuh/degenpad/degenpad.json
> +  "keycodes": [],
```suggestion

```

2023-02-17 02:17 UTC, ThePanduuh commented
Sorry about that. I must have done the V3 conversion in the V2 folder and was using that to test online. And then what was in the V3 folder was the beginning, prior to receipt of PCBs in my hands. 
Hopefully it's all good now.

2023-02-18 17:34 UTC, ThePanduuh commented
Merged into QMK :)

2023-02-19 10:17 UTC, yiancar commented
Cheers thanks!

2023-02-19 10:17 UTC, merged