Add cannonkeys bakeneko65 ISO hotswap
the-via/keyboards pull request #1810
Opened 2023-04-04 16:17 UTC by awkannan

## Description

Add CannonKeys Bakeneko65 Hotswap ISO PCB to VIA

## QMK Pull Request 

https://github.com/qmk/qmk_firmware/pull/20131
merged

## Checklist

- [ ] The VIA support for this keyboard is **MERGED** in QMK master already **(MANDATORY)**
- [ ] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [ ] I have a V3 JSON version for this keyboard definition.**(MANDATORY)**
- [ ] I have tested this keyboard definition using VIA's "Design" tab.
- [ ] I have tested this keyboard definition with firmware on a device.
- [ ] I have assigned alpha keys and modifier keys with the correct colors.
- [ ] The Vendor ID is not `0xFEED`

2023-04-08 04:24 UTC, Xelus22 requested changes

2023-04-08 04:24 UTC, Xelus22 commented on v3/cannonkeys/bakeneko65_iso_hs/bakeneko65_iso_hs.json
> +    "labels": [],
Remove empty labels

2023-04-26 20:37 UTC, awkannan commented
@Xelus22 all set!

2023-04-28 13:42 UTC, Xelus22 approved these changes

2023-04-28 13:42 UTC, merged