Add CannonKeys Bakeneko ISO Hotswap
the-via/keyboards pull request #1811
Opened 2023-04-04 16:22 UTC by awkannan

## Description

Add CannonKeys Bakeneko ISO Hotswap

## QMK Pull Request 
https://github.com/qmk/qmk_firmware/pull/20130
this is merged

## Checklist

- [x] The VIA support for this keyboard is **MERGED** in QMK master already **(MANDATORY)**
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have a V3 JSON version for this keyboard definition.**(MANDATORY)**
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

2023-04-08 04:25 UTC, Xelus22 requested changes

2023-04-08 04:25 UTC, Xelus22 commented on v3/cannonkeys/bakeneko60_iso_hs/bakeneko60_iso_hs.json
> +    "labels": [],
Remove empty labels

2023-04-26 20:36 UTC, awkannan commented
@Xelus22 all set!

2023-04-28 13:42 UTC, Xelus22 approved these changes

2023-04-28 13:42 UTC, merged