Add 7U support for creek70
the-via/keyboards pull request #1830
Opened 2023-04-16 03:23 UTC by spbgzh

## Description
<img width="1401" alt="image" src="https://user-images.githubusercontent.com/72414103/232264679-9ffa9c4b-26a0-49bc-88d8-c4d50b171554.png">

## QMK Pull Request 
https://github.com/qmk/qmk_firmware/pull/19789

## Checklist

- [x] The VIA support for this keyboard is **MERGED** in QMK master already **(MANDATORY)**
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have a V3 JSON version for this keyboard definition.**(MANDATORY)**
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

2023-04-16 16:13 UTC, spbgzh commented
It dont need to change anything in fireware because, it use same postions.
<img width="790" alt="CleanShot 2023-04-16 at 19 13 23@2x" src="https://user-images.githubusercontent.com/72414103/232325910-e51209b4-0ec1-4a56-a30d-1eb63b9cb9fa.png">

2023-04-22 12:43 UTC, Xelus22 requested changes
Why are you renaming Creek 70 to Epiphany 70? You will need to submit a new keyboard to QMK if you are adding a new keyboard.

2023-04-22 15:25 UTC, spbgzh commented
I will make a new PR to change keyboard's name

2023-04-24 08:40 UTC, Xelus22 approved these changes

2023-04-24 08:41 UTC, merged