Add KBDCraft Adam64
the-via/keyboards pull request #1831
Opened 2023-04-20 03:52 UTC by adophoxia

This will only add in the `v3` JSON for the Adam64 as `v2` are no longer required from what I understand.

## Description

## QMK Pull Request 

* https://github.com/qmk/qmk_firmware/pull/20503

## Checklist

- [ ] The VIA support for this keyboard is **MERGED** in QMK master already **(MANDATORY)**
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have a V3 JSON version for this keyboard definition.**(MANDATORY)**
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

2023-04-23 19:12 UTC, adophoxia commented
The board is now merged into [`qmk/qmk_firmware`](https://github.com/qmk/qmk_firmware/pull/20503), so best to get this merged.

2023-04-24 08:39 UTC, Xelus22 requested changes
Please add in the accents and modifiers. Everything else looks good.

2023-04-24 10:46 UTC, adophoxia commented
Colors for accents and modifiers have been added, @Xelus22.
![image](https://user-images.githubusercontent.com/100170946/233974455-6e36bb09-86ef-4b2f-834f-a5b6f60d65d6.png)

2023-04-24 10:46 UTC, Xelus22 approved these changes

2023-04-24 10:46 UTC, merged