Update adelais_en_ciel-rev3.json
the-via/keyboards pull request #1843
Opened 2023-05-04 04:24 UTC by mechlovin

## Description

Add VIA V3 support for encoder map, RGB backlit and RGB underglow.
Thanks.
## QMK Pull Request 

## Checklist

- [x] The VIA support for this keyboard is **MERGED** in QMK master already **(MANDATORY)**
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have a V3 JSON version for this keyboard definition.**(MANDATORY)**
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

2023-05-13 04:57 UTC, Xelus22 reviewed
Are you sure you want to remove the custom keycodes too? I see them in the keymap.c

2023-05-13 05:37 UTC, mechlovin commented
Thanks, added.

2023-05-13 08:02 UTC, Xelus22 requested changes

2023-05-13 08:02 UTC, Xelus22 commented on v3/mechlovin/adelais/adelais_en_ciel-rev3.json
> -  "keycodes": ["qmk_lighting"],
I recommend keeping this so the LIGHTING tab shows up in keycodes

![image](https://github.com/the-via/keyboards/assets/17491233/f8244d1b-8f77-4762-9ce8-82bf048cef10)

2023-05-14 07:21 UTC, Xelus22 approved these changes

2023-05-14 07:21 UTC, merged