Add Angle65
the-via/keyboards pull request #1845
Opened 2023-05-04 16:25 UTC by Vertex-kb

## Description
Add Angle65.
PCB production before V3 development, added V2/V3 for compatibility.Thanks！

## QMK Pull Request 

## Checklist

- [x] The VIA support for this keyboard is **MERGED** in QMK master already **(MANDATORY)**
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have a V3 JSON version for this keyboard definition.**(MANDATORY)**
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

2023-05-13 04:58 UTC, Xelus22 requested changes
![image](https://github.com/the-via/keyboards/assets/17491233/2de51354-671d-4fae-8f98-463cb51aa74f)
I'm not sure if the CLI likes this but can you rename then to lower case `json`?

2023-05-13 04:59 UTC, Xelus22 requested changes
https://www.caniusevia.com/docs/layouts#kle-json-rules

please use the correct colours for modifiers

2023-05-15 17:39 UTC, Vertex-kb commented
I have corrected. thanks！

2023-05-21 00:27 UTC, Xelus22 approved these changes

2023-05-21 00:27 UTC, merged