add noxary 378 v3 json
the-via/keyboards pull request #1864
Opened 2023-05-17 04:02 UTC by chupotle

## Description

I got tired of having to load the json every time.

## QMK Pull Request 

https://github.com/qmk/qmk_firmware/pull/13156

## Checklist

- [x] The VIA support for this keyboard is **MERGED** in QMK master already **(MANDATORY)**
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have a V3 JSON version for this keyboard definition.**(MANDATORY)**
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

2023-05-21 00:31 UTC, Xelus22 requested changes
https://www.caniusevia.com/docs/layouts#kle-json-rules

Looks good but could you please apply the colours? :D

2023-05-26 05:48 UTC, chupotle commented
> https://www.caniusevia.com/docs/layouts#kle-json-rules
> 
> Looks good but could you please apply the colours? :D

Just took care of it! https://i.imgur.com/jki8Aa3.png

2023-05-26 05:49 UTC, chupotle commented
im a clown

2023-05-28 06:46 UTC, Xelus22 approved these changes

2023-05-28 06:47 UTC, merged