Add Churrosoft Deck-8 macropad
the-via/keyboards pull request #1889
Opened 2023-06-03 20:54 UTC by Polsaker

## Description

Add Churrosoft's Deck-8 macropad.

## QMK Pull Request 

qmk/qmk_firmware#21119

## Checklist

- [X] The VIA support for this keyboard is **MERGED** in QMK master already **(MANDATORY)**
- [X] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [X] I have a V3 JSON version for this keyboard definition.**(MANDATORY)**
- [X] I have tested this keyboard definition using VIA's "Design" tab.
- [X] I have tested this keyboard definition with firmware on a device.
- [X] I have assigned alpha keys and modifier keys with the correct colors.
- [X] The Vendor ID is not `0xFEED`

2023-06-04 01:13 UTC, Xelus22 requested changes
It looks like your PID is actually `0xC101` in QMK?

`"keycodes": [ "qmk_lighting" ]`
you will want to add this so it shows up for users to add as keycode specific changing RGB.

2023-06-04 01:24 UTC, Polsaker commented
Hi! 

I actually noticed this while testing with the via website, but QMK is not honoring the pid override in the RGB variant's JSON file, so both firmwares end up with the 0xC100 variant. I'm going to add a second json file for the 0xC101 PID here and ask the QMK folks what's the best way to amend that

2023-06-04 01:26 UTC, Xelus22 commented
>  I'm going to add a second json file for the 0xC101 PID 
Just change this one to C101.

2023-06-04 01:27 UTC, Polsaker commented
> Just change this one to C101.

Yeah I actually meant to change this one to C101 and add a new file for the C100 non-rgb variant. That's now committed

2023-06-04 02:11 UTC, Polsaker commented
The issue I mentioned is now fixed in QMK master via qmk_firmware/pull#21126

2023-06-04 03:14 UTC, Xelus22 commented
Please add `"keycodes": [ "qmk_lighting" ]` as it will help this show 
![image](https://github.com/the-via/keyboards/assets/17491233/0a4fc045-f8f4-43e8-8c58-8f710af923f8)

2023-06-04 03:16 UTC, Polsaker commented
Done

2023-06-11 04:56 UTC, Xelus22 approved these changes

2023-06-11 04:57 UTC, merged