Add VIA support for Keychron C1 Pro
the-via/keyboards pull request #1912
Opened 2023-06-21 02:32 UTC by lalalademaxiya1

Added VIA JSONs for Keychron C1 Pro and request for a review, Thanks!

## Description

- Added c1_pro/c1_pro_ansi_rgb.json to v3/keychron.
- Added c1_pro/c1_pro_ansi_white.json to v3/keychron.
## QMK Pull Request 

qmk/qmk_firmware#20700

## Checklist

- [x] The VIA support for this keyboard is **MERGED** in QMK master already **(MANDATORY)**
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have a V3 JSON version for this keyboard definition.**(MANDATORY)**
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

2023-06-24 06:14 UTC, Xelus22 requested changes

2023-06-24 06:14 UTC, Xelus22 commented on v3/keychron/c1_pro/c1_us_rgb_v1.2.json
> +        "0,0\nESC",
Please remove ESC just incase.

2023-06-24 06:14 UTC, Xelus22 commented on v3/keychron/c1_pro/c1_us_white_v1.2.json
> +        "0,0\nESC",
Please remove ESC just incase

2023-06-24 08:25 UTC, lalalademaxiya1 commented on v3/keychron/c1_pro/c1_us_rgb_v1.2.json
> +        "0,0\nESC",
All right, thanks!

2023-07-01 13:18 UTC, Xelus22 approved these changes

2023-07-01 13:18 UTC, merged