Add json for Varanidae keyboard
the-via/keyboards pull request #1925
Opened 2023-07-01 09:57 UTC by TokageItLab

## Description

Add json for Varanidae keyboard recently merged in qmk_firmware.

## QMK Pull Request 

- https://github.com/qmk/qmk_firmware/pull/21340

## Checklist

- [x] The VIA support for this keyboard is **MERGED** in QMK master already **(MANDATORY)**
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have a V3 JSON version for this keyboard definition.**(MANDATORY)**
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

2023-07-01 13:23 UTC, Xelus22 requested changes
Please remove v2 definition (src/ folder version) as that is for legacy support of boards

2023-07-01 13:23 UTC, Xelus22 commented on v3/varanidae/varanidae.json
> +  "menus": [],
```suggestion
```

Remove unused json keys.

2023-07-01 14:40 UTC, TokageItLab commented on v3/varanidae/varanidae.json
> +  "menus": [],
Done, thanks.

2023-07-01 15:00 UTC, TokageItLab commented
Removede `src/varanidae`

2023-07-02 05:05 UTC, Xelus22 approved these changes

2023-07-02 05:06 UTC, merged