Add layout for Dactyl Manuform 5x6
the-via/keyboards pull request #1977
Opened 2023-08-03 10:58 UTC by hughrawlinson

## Description

Add VIA support for Dactyl Manuform 5x6

## QMK Pull Request 

[Merged QMK PR](https://github.com/qmk/qmk_firmware/pull/21649#event-9995815989)

## Checklist

- [x] The VIA support for this keyboard is **MERGED** in QMK master already **(MANDATORY)**
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have a V3 JSON version for this keyboard definition.**(MANDATORY)**
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

2023-08-05 01:46 UTC, Xelus22 requested changes

2023-08-05 01:46 UTC, Xelus22 commented on v3/handwired/dactyl_manuform/5x6/5x6.json
> +  "productId": "0x3538",
In QMK this is `0x3536`

2023-08-07 09:37 UTC, hughrawlinson commented on v3/handwired/dactyl_manuform/5x6/5x6.json
> +  "productId": "0x3538",
Fixed

2023-08-12 08:54 UTC, Xelus22 requested changes
Looks like this `5x6` conflicts with `5x6_5`

2024-01-24 12:09 UTC, closed without merging