Add support for CXT Studio
the-via/keyboards pull request #1981
Opened 2023-08-12 11:01 UTC by puffnfresh

## Description

## QMK Pull Request 

https://github.com/qmk/qmk_firmware/pull/21675

## Checklist

- [x] The VIA support for this keyboard is **MERGED** in QMK master already **(MANDATORY)**
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have a V3 JSON version for this keyboard definition.**(MANDATORY)**
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [ ] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

2023-08-13 11:54 UTC, Xelus22 requested changes

2023-08-13 11:54 UTC, Xelus22 commented on src/cxt/studio.json
> +  "productId": "0x12E3",
Different to the one in QMK

2023-08-13 11:55 UTC, Xelus22 requested changes
`"keycodes": [ "qmk_lighting" ]`

you'll likely want this too in here

2023-09-08 13:06 UTC, puffnfresh commented
@Xelus22 I've updated the PR, thanks for catching those issues.

2023-09-11 08:40 UTC, Xelus22 requested changes

2024-12-15 21:26 UTC, closed without merging