Add support to projectd_65_ansi keyboard
the-via/keyboards pull request #1983
Opened 2023-08-14 03:41 UTC by gskygithub

## Description

Add projectd_65_ansi keyboard

## QMK Pull Request 

https://github.com/qmk/qmk_firmware/pull/21520

## Checklist

- [x] The VIA support for this keyboard is **MERGED** in QMK master already **(MANDATORY)**
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have a V3 JSON version for this keyboard definition.**(MANDATORY)**
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [ ] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

2023-08-19 00:30 UTC, Xelus22 requested changes
https://www.caniusevia.com/docs/layouts#kle-json-rules

Please colour in your JSON keys

2023-08-21 02:32 UTC, gskygithub commented on v3/projectd/ansi/65/projectd_65_ansi.json
> +                ["HUE_BREATHING", 25]
@Xelus22 The other effects are not applying to keyboard even though I added.

2023-08-25 04:29 UTC, Xelus22 commented on v3/projectd/ansi/65/projectd_65_ansi.json
> +                ["HUE_BREATHING", 25]
You'll need to add them to this list. Or if you have enabled ALL effects, then you can use the default `"menus": ["qmk_rgb_matrix"],` and not have to use a custom one

example https://github.com/the-via/keyboards/blob/master/v3/xelus/pachi/xelus_pachi_rgb_rev1.json#L5-L6

2023-08-25 08:59 UTC, gskygithub commented
@Xelus22 Resolved requested changes, thanks.

2023-08-26 07:47 UTC, Xelus22 approved these changes

2023-08-26 07:47 UTC, merged