Adding support for TAN67 PCB
the-via/keyboards pull request #1992
Opened 2023-08-20 18:15 UTC by Pangorin

## Description
Adding VIA keymap support for TAN67 PCB

## QMK Pull Request 

https://github.com/qmk/qmk_firmware/pull/21003

## Checklist

- [x] The VIA support for this keyboard is **MERGED** in QMK master already **(MANDATORY)**
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have a V3 JSON version for this keyboard definition.**(MANDATORY)**
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

2023-08-20 18:16 UTC, Pangorin reviewed
Layouts

2023-08-26 07:44 UTC, Xelus22 commented
I believe these 3 keys are arrows? Should be white?
![image](https://github.com/the-via/keyboards/assets/17491233/441294d8-02c2-4748-ba7d-3bbf5d8335a5)

2023-08-26 17:41 UTC, Pangorin reviewed
Fix the layout.

2023-08-26 17:41 UTC, Pangorin commented
> I believe these 3 keys are arrows? Should be white? ![image](https://user-images.githubusercontent.com/17491233/263449830-441294d8-02c2-4748-ba7d-3bbf5d8335a5.png)

Yeah, I edited it!

2023-09-02 12:19 UTC, Xelus22 commented
Pleease check, build error

2023-09-11 08:44 UTC, Xelus22 requested changes

2023-09-11 08:44 UTC, Xelus22 commented on v3/pangorin/tan67/tan67.json
> +        {"x": 0.5, c:"#cccccc"},
```suggestion
        {"x": 0.5, "c":"#cccccc"},
```

2023-09-11 08:57 UTC, Xelus22 approved these changes

2023-09-11 08:57 UTC, merged