Add qk100 keyboard v2 and v3 files
the-via/keyboards pull request #1997
Opened 2023-08-22 08:22 UTC by owlab-git

## Description

## QMK Pull Request 

https://github.com/qmk/qmk_firmware/pull/21782

## Checklist

- [ ] The VIA support for this keyboard is **MERGED** in QMK master already **(MANDATORY)**
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have a V3 JSON version for this keyboard definition.**(MANDATORY)**
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

2023-10-24 04:55 UTC, owlab-git commented
Please check, thanks.

2023-10-29 00:34 UTC, Xelus22 requested changes
Please remove src/ folder ones. those are ONLY for legacy boards

2023-10-29 00:34 UTC, Xelus22 commented on v3/qwertykeys/qk100/qk100_ansi.json
> +  "menus": [
```suggestion
  "menus": [ "qmk_rgb_matrix" ],
```

you can replace the entire RGB block with this.

also you have rgb MATRIX enabled, not rgb LIGHT in your qmk firmware.

2023-10-29 00:34 UTC, Xelus22 commented on v3/qwertykeys/qk100/qk100_solder.json
> +  "menus": [
```suggestion
  "menus": [ "qmk_rgblight" ],
```

2023-10-29 00:34 UTC, Xelus22 commented on v3/qwertykeys/qk100/qk100_solder.json
> +      [
![image](https://github.com/the-via/keyboards/assets/17491233/fd6df849-cd2d-4699-9672-8122399115af)

suggest moving ISO out a bit (both files)
![image](https://github.com/the-via/keyboards/assets/17491233/12020b06-226e-4e45-9d94-bb4ed98b3697)

2023-11-05 22:45 UTC, merged