Update plywrks ply8x
the-via/keyboards pull request #2002
Opened 2023-08-29 12:45 UTC by ramonimbao

## Description

Removed `keycodes`. Switched from `qmk_rgblight` to `qmk_rgb_matrix`.

## QMK Pull Request 

https://github.com/qmk/qmk_firmware/pull/21263

## Checklist

- [x] The VIA support for this keyboard is **MERGED** in QMK master already **(MANDATORY)**
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have a V3 JSON version for this keyboard definition.**(MANDATORY)**
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

2023-09-02 12:10 UTC, Xelus22 requested changes

2023-09-02 12:10 UTC, Xelus22 commented on v3/plywrks/ply8x.json
> -  "keycodes": ["qmk_lighting"],
You should still keep this

2023-09-02 12:13 UTC, ramonimbao commented on v3/plywrks/ply8x.json
> -  "keycodes": ["qmk_lighting"],
Alright, I put it back

2023-09-03 00:56 UTC, Xelus22 approved these changes

2023-09-03 00:56 UTC, merged