adding Dawn keyboard support
the-via/keyboards pull request #2005
Opened 2023-08-30 13:30 UTC by dejaeghered

## Description

Adding support for Dawn

## QMK Pull Request 

https://github.com/qmk/qmk_firmware/pull/11564

## Checklist

- [x] The VIA support for this keyboard is **MERGED** in QMK master already **(MANDATORY)**
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have a V3 JSON version for this keyboard definition.**(MANDATORY)**
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

2023-09-02 12:00 UTC, Xelus22 requested changes
Please also create a V3 definition

2023-10-26 15:21 UTC, dejaeghered commented
@Xelus22 added thanks!

2023-10-29 00:45 UTC, Xelus22 requested changes

2023-10-29 00:45 UTC, Xelus22 commented on v3/mechstudio/dawn.json
> +    "menus": [],
```suggestion
```

2023-10-30 09:31 UTC, dejaeghered commented
confirmed

2023-11-05 22:23 UTC, Xelus22 approved these changes

2023-11-05 22:24 UTC, merged