add momokai aurora
the-via/keyboards pull request #2029
Opened 2023-09-26 18:11 UTC by peepeetee

## Description
Momokai aurora, a 6 key keypad with one encoder

## QMK Pull Request 

https://github.com/qmk/qmk_firmware/pull/20419

## Checklist

- [x] The VIA support for this keyboard is **MERGED** in QMK master already **(MANDATORY)**
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have a V3 JSON version for this keyboard definition.**(MANDATORY)**
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

2023-09-30 11:01 UTC, Xelus22 requested changes

2023-09-30 17:44 UTC, peepeetee commented on v3/momokai/momokai_aurora.json
> +    "menus": [
I have the impression that having less than all of the animations requires the corresponding list in VIA

2023-10-01 12:28 UTC, Xelus22 commented on v3/momokai/momokai_aurora.json
> +    "menus": [
Yes, but I think from counting you have all of them here? Unless im counting wrong.

2023-10-01 19:00 UTC, peepeetee commented on v3/momokai/momokai_aurora.json
> +    "menus": [
oooooooooo I must have missed it, will look into it. thanks!!!!!!!

2023-10-02 01:13 UTC, peepeetee commented on v3/momokai/momokai_aurora.json
> +    "menus": [
Changes applied. Thanks!!!!!!!!! I'll have it go in first before curating the list of animations

2023-10-02 11:30 UTC, Xelus22 approved these changes

2023-10-02 11:30 UTC, merged