Add support to jk01 keyboard
the-via/keyboards pull request #2057
Opened 2023-10-20 10:58 UTC by gskygithub

## Description

Add jukaie/jk01 keyboard

## QMK Pull Request 

https://github.com/qmk/qmk_firmware/pull/20573

## Checklist

- [x] The VIA support for this keyboard is **MERGED** in QMK master already **(MANDATORY)**
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have a V3 JSON version for this keyboard definition.**(MANDATORY)**
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [ ] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

2023-10-22 08:14 UTC, Xelus22 requested changes

2023-10-22 08:14 UTC, Xelus22 commented on v3/jukaie/jk01/jk01.json
> +    {"name": "File Explorer", "title": "File Explorer in windows", "shortName": "File Explorer"}
I don't see any custom keycodes in your QMK source files.
Please remove these.

2023-10-23 07:47 UTC, Xelus22 requested changes
![image](https://github.com/the-via/keyboards/assets/17491233/78a14f3c-516f-4e3d-b25e-f6f2fdc34805)

please colour in the KLE https://www.caniusevia.com/docs/layouts#kle-json-rules

2023-10-29 00:28 UTC, Xelus22 requested changes
Still havent fixed it
![image](https://github.com/the-via/keyboards/assets/17491233/456fa48d-0b8e-4937-9f28-ddd0fc8c893a)

2023-10-30 08:53 UTC, gskygithub commented
> Still havent fixed it ![image](https://user-images.githubusercontent.com/17491233/278843234-456fa48d-0b8e-4937-9f28-ddd0fc8c893a.png)

@Xelus22 For me, it is looking normal in VIA.
![image](https://github.com/the-via/keyboards/assets/106651989/8e97044b-7c53-4010-a76a-2c067062b30d)

2023-11-05 22:33 UTC, Xelus22 commented
Please follow the VIA docs. Alphas are cccccc, and the mods and accents. It looks different when you go to settings and change the theme.

2023-11-14 03:00 UTC, gskygithub commented
@Xelus22 Resolved requested changes, please take a look, thanks.

2023-11-20 07:38 UTC, Xelus22 approved these changes

2023-11-20 07:38 UTC, merged