add keyboard bestway
the-via/keyboards pull request #2093
Opened 2023-12-01 11:12 UTC by LXF-YZP

## Description
add keyboard bestway

## QMK Pull Request 
[qmk/qmk_firmware/pull/22498](https://github.com/qmk/qmk_firmware/pull/22498)

## Checklist

- [x] The VIA support for this keyboard is **MERGED** in QMK master already **(MANDATORY)**
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have a V3 JSON version for this keyboard definition.**(MANDATORY)**
- [ ] I have tested this keyboard definition using VIA's "Design" tab.
- [ ] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

2023-12-02 06:35 UTC, Xelus22 requested changes

2023-12-02 06:35 UTC, Xelus22 commented on v3/bestway/best.json
> +    "name": "Best70",
Rename file to `bestway.json`

The name is Best70 but in QMK it says just `Best`.
Please keep one of them to be consistent

2023-12-02 06:35 UTC, Xelus22 commented on v3/bestway/best.json
> +      ],
```suggestion
    "menus": [ "qmk_rgblight" ],
    "keycodes": ["qmk_lighting"],
```

can be simplified to this

2023-12-02 09:41 UTC, LXF-YZP commented on v3/bestway/best.json
> +      ],
thank you for your help

2024-02-03 01:09 UTC, Xelus22 approved these changes

2024-02-03 01:09 UTC, merged