Proteus67 addition
the-via/keyboards pull request #2140
Opened 2024-01-15 13:23 UTC by gzowski

## Description

Proteus67 keyboard layout

## QMK Pull Request 

merged to to master
https://github.com/qmk/qmk_firmware/pull/22439

## Checklist

- [x] The VIA support for this keyboard is **MERGED** in QMK master already **(MANDATORY)**
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have a V3 JSON version for this keyboard definition.**(MANDATORY)**
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

2024-02-03 01:16 UTC, Xelus22 approved these changes

2024-02-03 01:17 UTC, Xelus22 requested changes

2024-02-03 01:17 UTC, Xelus22 commented on v3/proteus67/proteus67.json
> +   "menus": ["qmk_rgblight"],
```suggestion
	"keycodes": [ "qmk_lighting" ],
   "menus": ["qmk_rgblight"],
```

Missing the keycodes option

2024-02-03 12:31 UTC, gzowski commented on v3/proteus67/proteus67.json
> +   "menus": ["qmk_rgblight"],
added keycodes option as suggested.

2024-02-11 02:28 UTC, Xelus22 approved these changes

2024-02-11 02:28 UTC, merged