Create haven60.json
the-via/keyboards pull request #2228
Opened 2024-04-04 06:43 UTC by CMMS-Freather

add haven60 json

adding ah haven60 via support

## Description

adding ah haven60 via support
## QMK Pull Request 

https://github.com/qmk/qmk_firmware/pull/23062

## Checklist

- [x] The VIA support for this keyboard is **MERGED** in QMK master already **(MANDATORY)**
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have a V3 JSON version for this keyboard definition.**(MANDATORY)**
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

2024-04-04 23:02 UTC, dunk2k requested changes
- add 0.25 padding
- add WKL and HHKB bottom row options
- correct key colouring

2024-04-08 10:14 UTC, dunk2k requested changes
general formatting

2024-04-08 10:14 UTC, dunk2k commented on v3/ah/haven60.json
> +
```suggestion
```

2024-04-08 10:14 UTC, dunk2k commented on v3/ah/haven60.json
> +  ],
```suggestion
  "keycodes": [
    "qmk_lighting"
  ],
  "menus": [
    "qmk_rgblight"
  ],
  "matrix": {
    "rows": 5,
    "cols": 14
  },
  "layouts": {
    "labels": [
      "Split Backspace",
      "ISO Enter",
      "Split Left Shift",
      "Split Right Shift",
      [
        "Bottom Row",
        "Full",
        "WKL",
        "HHKB (7u)"
      ]
    ],
```

2024-04-08 10:14 UTC, dunk2k commented on v3/ah/haven60.json
> +        {"c": "#cccccc"},
```suggestion
        {
          "c": "#cccccc"
        },
```

2024-04-09 14:26 UTC, dunk2k approved these changes

2024-05-31 12:45 UTC, Xelus22 approved these changes

2024-05-31 12:45 UTC, merged