add crafwalk
the-via/keyboards pull request #2295
Opened 2024-06-01 15:57 UTC by sotoba

## Description

add craftwalk support

## QMK Pull Request

- https://github.com/qmk/qmk_firmware/pull/23658
- https://github.com/qmk/qmk_firmware/pull/23808

## Checklist

- [x] The VIA support for this keyboard is **MERGED** in QMK master already **(MANDATORY)**
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have a V3 JSON version for this keyboard definition.**(MANDATORY)**
- [x] I have formatted the JSON file to have consistent formatting with the rest of the repository.
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

2024-06-02 05:16 UTC, Xelus22 requested changes

2024-06-02 05:16 UTC, Xelus22 commented on v3/craftwalk/craftwalk.json
> +    "menus": ["qmk_rgblight"],
```suggestion
    "menus": ["qmk_rgblight"],
    "keycodes": [ "qmk_lighting" ],
```

2024-06-02 05:16 UTC, Xelus22 commented on v3/craftwalk/craftwalk.json
> +    "menus": ["qmk_rgblight"],
Adds RGB keycodes

2024-06-02 08:30 UTC, sotoba commented on v3/craftwalk/craftwalk.json
> +    "menus": ["qmk_rgblight"],
thx!

2024-06-07 11:42 UTC, Xelus22 approved these changes

2024-06-07 11:42 UTC, merged