add jaykeeb jk60
the-via/keyboards pull request #2300
Opened 2024-06-11 01:56 UTC by alabahuy

## Description

add jaykeeb jk60, layout 60% support many case existing

## QMK Pull Request

https://github.com/qmk/qmk_firmware/pull/23876

## Checklist

- [ ] The VIA support for this keyboard is **MERGED** in QMK master already **(MANDATORY)**
- [ ] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [ ] I have a V3 JSON version for this keyboard definition.**(MANDATORY)**
- [ ] I have formatted the JSON file to have consistent formatting with the rest of the repository.
- [ ] I have tested this keyboard definition using VIA's "Design" tab.
- [ ] I have tested this keyboard definition with firmware on a device.
- [ ] I have assigned alpha keys and modifier keys with the correct colors.
- [ ] The Vendor ID is not `0xFEED`

2024-06-16 08:57 UTC, dunk2k requested changes

2024-06-16 08:57 UTC, dunk2k commented on v3/jaykeeb/jk60/jk60.json
> +      ["Bottom Row", "6.25U", "Tsangan", "WKL", "HHKB"]
formatting
```suggestion
  "matrix": {
    "rows": 5,
    "cols": 14
  },
  "layouts": {
    "labels": [
      "Split Backspace",
      "Split LShift",
      "Split RShift",
      [
        "Bottom Row",
        "6.25U",
        "Tsangan",
        "WKL",
        "HHKB"
      ]
```

2024-07-06 07:43 UTC, Xelus22 requested changes
![image](https://github.com/the-via/keyboards/assets/17491233/93c86682-5cf4-43d6-8416-03ba5e7df0e0)


This will require decals

https://www.caniusevia.com/docs/layouts#layout-options

2024-07-06 10:25 UTC, alabahuy commented
> ![image](https://private-user-images.githubusercontent.com/17491233/346259558-93c86682-5cf4-43d6-8416-03ba5e7df0e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyNjA3NDYsIm5iZiI6MTcyMDI2MDQ0NiwicGF0aCI6Ii8xNzQ5MTIzMy8zNDYyNTk1NTgtOTNjODY2ODItNWNmNC00M2Q2LTg0MTYtMDNiYTVlN2RmMGUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA2VDEwMDcyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzNDVmODBmODMxMjFhODZjY2FhOGIxNmQ5OWNmMGFkNzY0ZjJiN2I1N2E1OWYwMGViOTFiZWE4ODljYmFkMmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aGPUNx99tUgaU_rXZNri9M5o0EbNlw6z5kUY146sOWI)
> 
> This will require decals
> 
> https://www.caniusevia.com/docs/layouts#layout-options

oke done

2024-07-06 13:51 UTC, Xelus22 approved these changes

2024-07-06 13:51 UTC, merged