Add Cycle7
the-via/keyboards pull request #2309
Opened 2024-06-23 02:05 UTC by Vertex-kb

## Description
Add Cycle7 

## QMK Pull Request
https://github.com/qmk/qmk_firmware/pull/23290

## Checklist

- [x] The VIA support for this keyboard is **MERGED** in QMK master already **(MANDATORY)**
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have a V3 JSON version for this keyboard definition.**(MANDATORY)**
- [x] I have formatted the JSON file to have consistent formatting with the rest of the repository.
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

2024-07-06 07:49 UTC, Xelus22 requested changes
Please remove V2 version (src/ folder one) as this is legacy and we do not accept anymore pull requests for them.

2024-07-23 02:26 UTC, Vertex-kb commented
Hello, the firmware at that time was version V2, and these PCBs have already been in the hands of users. Can you be accommodating?

2024-07-27 06:40 UTC, Xelus22 commented
> Hello, the firmware at that time was version V2, and these PCBs have already been in the hands of users. Can you be accommodating?

Your QMK PR was only 2 months ago, V2 has been deprecated for at least 1 year already.

2024-07-29 09:55 UTC, dunk2k requested changes

2024-07-29 09:55 UTC, dunk2k commented on src/vertex/cycle7/cycle7.json
as per comments, please delete this file

2024-07-29 09:55 UTC, dunk2k commented on v3/vertex/cycle7/cycle7.json
> +["Bottom Row", "Ansi", "Tsangan","Wkl"]
please format this section of code

2024-10-08 20:24 UTC, Cipulot commented
VIA Keymap moved after last QMK Breaking Changes: https://github.com/the-via/qmk_userspace_via/tree/main/keyboards/vertex/cycle7/keymaps/via

The PR opener should delete the V2 defs since they are not needed nor used and apply the formatting of the json in V3.

2024-12-15 21:33 UTC, closed without merging