Add missing layout for XD60
the-via/keyboards pull request #415
Opened 2020-11-17 20:02 UTC by Stuxles

## Description

Added missing layout where right shift is split but aligned to the left

## QMK Pull Request 

## Checklist

- [ ] The QMK source code follows the guide here: https://caniusevia.com/docs/configuring_qmk / no QMK code edited
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

2020-12-10 07:33 UTC, se-bastiaan requested changes
Could you also make these changes for the rev3?

2020-12-10 17:23 UTC, Stuxles commented
> Could you also make these changes for the rev3?


Made the same changes to the rev3 👍

2020-12-10 17:34 UTC, se-bastiaan approved these changes

2021-01-03 21:11 UTC, Stuxles commented
https://github.com/the-via/keyboards/pull/485 is the right solution to this problem, closing this pull request in favor of that one.

2021-01-03 21:11 UTC, closed without merging