Add jd45 keyboard
the-via/keyboards pull request #687
Opened 2021-04-21 07:28 UTC by matthewdias

Pending qmk reorg

## QMK Pull Request 

https://github.com/qmk/qmk_firmware/pull/12520

## Checklist

- [ ] The VIA support for this keyboard is in QMK master already (MANDATORY)
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

2021-04-21 07:48 UTC, wilba requested changes

2021-04-21 07:48 UTC, wilba commented on src/jd45/jd45.json
> +  "productId": "0x6060",
```suggestion
  "vendorId": "0x6582",
  "productId": "0x0004",
```

2021-04-21 07:48 UTC, wilba commented on src/jd45/jd45.json
> +      ["Bottom Row", "Split Space", "6.25u", "6u"]
```suggestion
      ["Bottom Row", "Split Space", "6.25U", "6U"]
```

2021-04-21 07:50 UTC, wilba commented
Make these changes, I'll merge now and then move it to `wilba_tech` later.
You can build your own QMK firmware with the changed VID/PID in the short term.

2021-04-24 04:47 UTC, matthewdias commented
Done. Thanks for doing that!

2021-04-24 12:58 UTC, merged