Add ZSA Moonlander
the-via/keyboards pull request #963
Opened 2021-09-25 20:32 UTC by MiddleMan5

## Description

Add ZSA Moonlander MK1 support

## QMK Pull Request 
https://github.com/qmk/qmk_firmware/pull/14603

## Checklist

- [ ] The VIA support for this keyboard is in QMK master already **(MANDATORY)**
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

Tested with VIA:
![image](https://user-images.githubusercontent.com/12738069/134785268-1be20926-e694-435c-981e-1a41bb96509d.png)

2021-09-27 21:32 UTC, drashna requested changes

2021-09-27 21:32 UTC, drashna commented on src/zsa/moonlander.json
> +  "lighting": "qmk_rgblight",
```suggestion
    "lighting": {
      "extends": "qmk_rgblight",
      "keycodes": "qmk",
      "underglowEffects": [
        ["Off", 0],
        ["Solid Color", 1],
        ["Alpha Mods", 1],
        ["Gradient Up-Down", 1],
        ["Gradient Left-Right", 1],
        ["Breathing", 1],
        ["Band Saturation", 1],
        ["Band Brightness", 1],
        ["Band Pinwheel Saturation", 1],
        ["Band Pinwheel Brightness", 1],
        ["Band Spiral Saturation", 1],
        ["Band Spiral Brightness", 1],
        ["Gradient", 1],
        ["Gradient Cycle Left-Right", 1],
        ["Gradient Cycle Up-Down", 1],
        ["Cycle In", 1],
        ["Cycle In (Dual)", 1],
        ["Rainbow Chevron", 1],
        ["Gradient Pinwheel", 1],
        ["Gradient Spiral", 1],
        ["Gradient Dual Beacon", 1],
        ["Gradient Beacon", 1],
        ["Dual Pinwheel", 1],
        ["Raindrops", 1],
        ["Jellybean Raindrops", 1],
        ["Hue Breathing", 1],
        ["Hue Bendulum", 1],
        ["Hue Wave", 1],
        ["Heatmap", 1],
        ["Digitial Rain", 1],
        ["Reactive (Simple)", 1],
        ["Reactive", 1],
        ["Reactive Wide", 1],
        ["Reactive Wide (Multi)", 1],
        ["Reactive Cross", 1],
        ["Reactive Cross (Multi)", 1],
        ["Reactive Nexus", 1],
        ["Reactive Nexus (Multi)", 1],
        ["Splash (Multi-Color)", 1],
        ["Splash (Multi-Color) (Multi)", 1],
        ["Splash (Solid Color)", 1],
        ["Splash (Solid Color) (Multi)", 1]
      ]
    },
```

2021-09-27 21:32 UTC, drashna commented on src/zsa/moonlander.json
> +    ]
```suggestion
      [
        {
          "x": 3.5
        },
        "0,3",
        {
          "x": 11.5
        },
        "6,3"
      ],
      [
        {
          "y": -0.875,
          "x": 2.5
        },
        "0,2",
        {
          "x": 1
        },
        "0,4"
      ],
      [
        {
          "y": -0.995,
          "x": 15
        },
        "6,2",
        {
          "x": 1
        },
        "6,4"
      ],
      [
        {
          "y": -0.88,
          "x": 5.5
        },
        "0,5",
        "0,6",
        {
          "x": 5.5
        },
        "6,0",
        "6,1"
      ],
      [
        {
          "y": -0.875,
          "x": 0.5
        },
        "0,0",
        "0,1"
      ],
      [
        {
          "y": -0.995,
          "x": 18
        },
        "6,5",
        "6,6"
      ],
      [
        {
          "y": -0.38,
          "x": 3.5
        },
        "1,3",
        {
          "x": 11.5
        },
        "7,3"
      ],
      [
        {
          "y": -0.875,
          "x": 2.5
        },
        "1,2",
        {
          "x": 1
        },
        "1,4"
      ],
      [
        {
          "y":-1,
          "x": 15
        },
        "7,2",
        {
          "x": 1
        },
        "7,4"
      ],
      [
        {
          "y": -0.8799999999999999,
          "x": 5.5
        },
        "1,5",
        "1,6",
        {
          "x": 5.5
        },
        "7,0",
        "7,1"
      ],
      [
        {
          "y": -0.875,
          "x": 0.5
        },
        "1,0",
        "1,1"
      ],
      [
        {
          "y":-1,
          "x": 18
        },
        "7,5",
        "7,6"
      ],
      [
        {
          "y": -0.3799999999999999,
          "x": 3.5
        },
        "2,3",
        {
          "x": 11.5
        },
        "8,3"
      ],
      [
        {
          "y": -0.875,
          "x": 2.5
        },
        "2,2",
        {
          "x": 1
        },
        "2,4"
      ],
      [
        {
          "y":-1,
          "x": 15
        },
        "8,2",
        {
          "x": 1
        },
        "8,4"
      ],
      [
        {
          "y": -0.8799999999999999,
          "x": 5.5
        },
        "2,5",
        "2,6",
        {
          "x": 5.5
        },
        "8,0",
        "8,1"
      ],
      [
        {
          "y": -0.875,
          "x": 0.5
        },
        "2,0",
        "2,1"
      ],
      [
        {
          "y":-1,
          "x": 18
        },
        "8,5",
        "8,6"
      ],
      [
        {
          "y": -0.3799999999999999,
          "x": 3.5
        },
        "3,3",
        {
          "x": 11.5
        },
        "9,3"
      ],
      [
        {
          "y": -0.875,
          "x": 2.5
        },
        "3,2",
        {
          "x": 1
        },
        "3,4"
      ],
      [
        {
          "y":-1,
          "x": 15
        },
        "9,2",
        {
          "x": 1
        },
        "9,4"
      ],
      [
        {
          "y": -0.8799999999999999,
          "x": 5.5
        },
        "3,5",
        {
          "x": 0.5,
          "c": "#777777",
          "w": 2
        },
        "5,3",
        {
          "x": 2.5,
          "w": 2
        },
        "11,3",
        {
          "x": 0.5,
          "c": "#cccccc"
        },
        "9,1"
      ],
      [
        {
          "y": -0.875,
          "x": 0.5
        },
        "3,0",
        "3,1"
      ],
      [
        {
          "y":-1,
          "x": 18
        },
        "9,5",
        "9,6"
      ],
      [
        {
          "y": -0.3799999999999999,
          "x": 3.5,
          "c": "#777777"
        },
        "4,3",
        {
          "x": 11.5
        },
        "10,3"
      ],
      [
        {
          "y": -0.875,
          "x": 2.5,
          "c": "#cccccc"
        },
        "4,2",
        {
          "x": 1,
          "c": "#777777"
        },
        "4,4"
      ],
      [
        {
          "y":-1,
          "x": 15
        },
        "10,2",
        {
          "x": 1,
          "c": "#cccccc"
        },
        "10,4"
      ],
      [
        {
          "y": -0.8799999999999999,
          "x": 7,
          "h": 1.5
        },
        "5,0",
        {
          "h": 1.5
        },
        "5,1",
        {
          "h": 1.5
        },
        "5,2",
        {
          "x": 0.5,
          "h": 1.5
        },
        "11,4",
        {
          "h": 1.5
        },
        "11,5",
        {
          "h": 1.5
        },
        "11,6"
      ],
      [
        {
          "y": -0.875,
          "x": 0.5
        },
        "4,0",
        "4,1"
      ],
      [
        {
          "y": -1,
          "x": 18
        },
        "10,5",
        "10,6"
      ]
    ]
```

2021-11-02 22:56 UTC, wilba commented
@MiddleMan5 can you address the suggestions from @drashna please

2021-11-14 05:01 UTC, MiddleMan5 reviewed
Updated, sorry for the delay

2021-11-15 17:19 UTC, drashna approved these changes

2021-12-29 05:56 UTC, Glutnix commented
is there a hold up with this PR? It'd be swell to get this usable.

2022-02-28 01:53 UTC, merged